### PR TITLE
Create new playground

### PR DESCRIPTION
**Pull request by ksketo**
Create better interface for the demo playground

### CODE REVIEW

**Comment by maierfelix** [comment]
LGTM, please resolve the conflicts

**Comment by ksketo** [comment]
I had removed the index.html. Resolved now. Thanks

**Comment by maierfelix** [comment]
Can now be reached [here](http://www.felixmaier.info/momo/playground/playground.html)
There are errors in the console

**Comment by ksketo** [comment]
Will fix asap

**Comment by maierfelix** [comment]
Also please rename ``playground.html`` => ``index.html``

**Pull request merged**
