### PR TITLE
Proper Unit tests, Rollup build, npm config, eslint

### PR DESCRIPTION
**Pull request by ballercat**
Hello,

First, I'd like to say thank you, for all the work you've put into this. I think this is an excellent idea and is very exciting project.

I would like to contribute to what you're doing here, but I have found it very difficult to work with the codebase as it is now. The main problem **is it's hard to test changes**, for two main reasons:
* There is no build process. There is no documentation on how to build the project or what is the preferred way.
* There is no unit tests. The test files are self-descriptive but it is not clear how you run these.

This MR aims to fix both of these. I'd like to add the following to this project:
* NPM config. I left this pretty basic, so I'm open to what you want in there as far as version etc.
* Rollup build. Production and dev
* `dist/` files checked into the repository for quick testing and experimentation.
* `ava` test runner. This included changing the format of the test files. The tests themselves are as before but now with a nicer automated `npm test` command.

## Merge conflicts
I had to make quite a few changes to make everything compile into a single bundle. I've tried to do it a couple of times but I seem to constantly run into major merge conflicts. I'm willing to put the time into resolving these if my changes are welcomed.

## This MR is _mostly_ about the tests

I think they are super helpful, encouraging both correctness and experimentation. I've already caught an assignment bug with them. For a project like this one, a compiler (even a small one) it's tough to get into without some backup. And I think automated-testing will provide that.

### CODE REVIEW

**Comment by maierfelix** [comment]
Hi there,

I'm running the tests with node/test.js. The assignment bugs occurred after moving variables into memory and is known. The code base lacks quality, I know. I want the compiler to get self-hosted in the future, so I'm using minimal and easily portable javascript without focusing on a good project structure.

I have no experience with Ava, but if future versions of this project (a C source) won't conflict with the tests and base structure (and you are willed to help if so), then nothing stands between this getting merged as soon as the conflicts are resolved.

I generally lack experience of providing good code bases, so thanks for this and you're welcome!

**Comment by ballercat** [comment]
Thanks for the quick response!

These merge conflicts were rough but I think I have everything back to desired state. 

I decided not to mess with your current setup of tests and left the original files alone. I added another directory for the "unit" tests.

I want to make sure I din't cause a regression by merge resolution as now I'm seeing a pointer test fail as well, but judging by the comment in it, seems like you already know about it.

**Comment by maierfelix** [comment]
The failing pointer test is related to a future feature (incr/decr pointers) which will come with array and struct support. Placed it there to don't forget about it :p 

As tests will be done with Ava -> I'd like to add an ``assert`` function to the compiler tomorrow, so tests can be placed inside ``.c`` files. Will this work together with Ava?

**Comment by ballercat** [comment]
I wan't to say _yes_ it will work, but it's hard to answer _how_ as I'm not sure what `assert` does. Does `assert` throw an Exception when it fails? If it does, it would be trivial to test.

**Comment by maierfelix** [comment]
````c
int main() {
  assert(1 == 1);
  assert(1 < 2);
};
````
`assert` could be linked to a imported js function and throws if the condition is false. This way we could use ``.c`` files and check multiple cases inside them.
````js
let assert = (truth) => {
  if (!truth) { // do something }
};
````
``assert`` could then be linked to Ava or am I misunderstanding it's concept?

**Comment by ballercat** [comment]
Oh I see, that would work for sure. It would be interesting to see it encoded into `.wasm` directly though with [unreachable](http://webassembly.org/docs/binary-encoding/#control-flow-operators-described-here). It seems to do what you would want, but importing it through JS may be easier to implement.

**Comment by maierfelix** [comment]
Interesting, played around with ``unreachable`` and it's even possible to assign function names to the produced stack trace (error traces just give the function indices). Thanks for this neat tip

**Comment by ballercat** [comment]
Alright I think this is a good state. Let me know if you'd like any other changes.

**Comment by maierfelix** [comment]
Good work!

**Pull request merged**
